### ISSUE TITLE
Error: 'module' object has no attribute '<some-random-thing>'

### ISSUE THREAD

**Issue by Kiefy** [cmcpasserby/pbUDK#2]
Not sure what I'm doing wrong. Plugin is loaded in Maya 2014 SP2

Wasn't sure if the files should be extracted to global `\maya\` or version specific `\maya\2014-x64\`  Tried both anyway. same result.

The first time I tried to launch in the Python editor, it complained that <module> was missing attribute MayaHIK, which I recognised as a plugin, disabled it and then the error changed to something different like xgmBlahblah, but always something.

![Error](http://image.prntscr.com/image/8562d6e252af403094a1e47dfd713ed9.png)

```
# pymel.core : Updating pymel with pre-loaded plugins: DirectConnect, mayaHIK, AbcImport, tiffFloatReader, xgenToolkit, VectorRender, gpuCache, rotateHelper, xgenMR, MayaMuscle, Substance, AutodeskPacketFile, autoLoader, fbxmaya, matrixNodes, ik2Bsolver, modelingToolkit, OpenEXRLoader, ikSpringSolver, Mayatomr, DDConvexHull-2014_64bit, AbcExport, ArubaTessellator, quatNodes, mayaCharacterization, OneClick, retargeterNodes, sceneAssembly # 
# Warning: pymel.internal.factories : could not create a PyNode for manipulator type xgmGuideManip # 
# Warning: pymel.internal.factories : could not create a PyNode for manipulator type xgmPointsManip # 
# Warning: pymel.internal.factories : could not create a PyNode for manipulator type igBrushManip # 
# Error: line 1: 'module' object has no attribute 'apfEntityNode'
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "C:/Users/Kief/Documents/maya/2014-x64/scripts\pbUDK.py", line 4, in <module>
#     import pymel.core as pm
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 297, in <module>
#     _installCallbacks()
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 295, in _installCallbacks
#     _pluginLoaded( plugin )
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 134, in _pluginLoaded
#     _addPluginCommand(pluginName, funcName)
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 63, in _addPluginCommand
#     _pmcmds.addWrappedCmd(funcName)
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\internal\pmcmds.py", line 115, in addWrappedCmd
#     cmd = getattr(maya.cmds, cmdname)
# AttributeError: 'module' object has no attribute 'apfEntityNode' #
```

**Comment by cmcpasserby** [comment]
since it seems to be failing, on the pymel import, can you let me know if you get any errors if you run
`import pymel.core as pm`
in the script editor.

**Comment by Kiefy** [comment]
Yeah, same deal.  fresh install too.  what's the prognosis Doc?

```
import pymel.core as pm
# pymel.internal.factories : MFnDagNode.model is deprecated # 
# pymel.core : Updating pymel with pre-loaded plugins: DirectConnect, mayaHIK, AbcImport, tiffFloatReader, xgenToolkit, VectorRender, gpuCache, xgenMR, rotateHelper, Substance, MayaMuscle, AutodeskPacketFile, autoLoader, fbxmaya, matrixNodes, ik2Bsolver, modelingToolkit, OpenEXRLoader, ikSpringSolver, Mayatomr, DDConvexHull-2014_64bit, AbcExport, ArubaTessellator, quatNodes, mayaCharacterization, OneClick, retargeterNodes, sceneAssembly # 
# Error: line 1: 'module' object has no attribute 'HIKComputeReference'
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 297, in <module>
#     _installCallbacks()
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 295, in _installCallbacks
#     _pluginLoaded( plugin )
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 134, in _pluginLoaded
#     _addPluginCommand(pluginName, funcName)
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 63, in _addPluginCommand
#     _pmcmds.addWrappedCmd(funcName)
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\internal\pmcmds.py", line 115, in addWrappedCmd
#     cmd = getattr(maya.cmds, cmdname)
# AttributeError: 'module' object has no attribute 'HIKComputeReference' # 
```

**Comment by cmcpasserby** [comment]
am not exactly sure, but the issue seems to be with your Maya install. Is this a normal out of the box maya install or is it something your work has setup.

Also considering the error you are now getting is part of the pymel module it might be worth looking here.
@LumaPictures
https://github.com/LumaPictures/pymel

**Comment by Kiefy** [comment]
I uninstalled everything relating to 2014 (Still have 2016 installed) and got the latest installer from Autodesk for 2014 SP4.  After install, no change..

Guess I'll go bug the pyMel team.

Thanks for help! :)

**Comment by Kiefy** [comment]
Ok well, I feel silly.  Turns out there was something in my \Docs\maya\ that was conflicting. If I determine what it was, I'll update here.

Thanks again @cmcpasserby. Now it is time to get to grips with your awesome tool. :)

**Comment by cmcpasserby** [comment]
yeah cool, if you run into any other problems let me know, since i have not had much time to test the tool on my end.

**Comment by Kiefy** [comment]
I found the source of the problem.

I'm using a pre-release version of Epic's [Animation and Rigging Tools](https://forums.unrealengine.com/showthread.php?2447-Animation-and-Rigging-Tools-FAQ-Known-Issues-and-Feature-Roadmap)

Adding their updated `userSetup.py` to `\scripts\` breaks your tool and pyMel?  The stable version bundled with UE4.12 is fine.
